enable-debug: false

# Auto-convert items on plugin enable
auto-convert-on-startup: false

# Default material for items
default-material: "PAPER"

# Disable italic formatting in item lore by adding <!i> tag
disable-default-italic: true